name: telegram_ui_joseph
description: Telegram UI clone. Implementation of home and drawer UIs.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true
  assets:
    - assets/joseph.jpg
    - assets/icon/

  fonts:
    - family: Telegram
      fonts:
        - asset: assets/font/rmono.ttf
          weight: 400
        - asset: assets/font/rmedium.ttf
          weight: 500
        - asset: assets/font/rcondensedbold.ttf
          weight: 700
